[package]
name = "advent-of-code-2015"
version = "0.1.0"
authors = ["Tim Oram <dev@mitmaro.ca>"]

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.9.0"
md-5 = "0.9.1"
