[package]
name = "advent-of-code-2015"
version = "0.1.0"
authors = ["Tim Oram <dev@mitmaro.ca>"]
edition = "2021"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.10.3"
md-5 = "0.10.0"
serde_json = "1.0.72"
